node {

    def userInput

    stage ('Setup') {
        echo 'Creating a new release'

        timeout(time:60, unit:'SECONDS') {
            userInput = input(
                    id: 'userInput', message: 'Create a new release', parameters: [
                    [$class: 'TextParameterDefinition', defaultValue: 'master', name: 'Branch'],
                    [$class: 'TextParameterDefinition', defaultValue: '0.0.1', name: 'Version']
            ])
        }
    }

    stage ('Checkout and Build') {
        git url: "https://github.com/svenjohann/gs-spring-boot-docker.git", branch: userInput['Branch'], credentialsId: '5c669a2d-fcc8-48cc-8f35-a000a6267788'
        def version = userInput['Version']
        dir ("complete") {
            def pom = readMavenPom file: 'pom.xml'
            pom.version = version
            writeMavenPom model: pom
            sh "mvn -e clean install docker:build -DdockerImageTags=" + version + " -DpushImage"
        }
    }

}
